//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clean_Planet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CleanPlanetEntities : DbContext
    {
        public CleanPlanetEntities()
            : base("name=CleanPlanetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_type_import> Material_type_import { get; set; }
        public DbSet<Partner_services_import> Partner_services_import { get; set; }
        public DbSet<Partners_import> Partners_import { get; set; }
        public DbSet<Service_type_import> Service_type_import { get; set; }
        public DbSet<Services_import> Services_import { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
