//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clean_Planet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_services_import
    {
        public int ID { get; set; }
        public string Услуга { get; set; }
        public string Наименование_партнера { get; set; }
        public Nullable<double> Количество_услуг { get; set; }
        public string Дата_выполнения { get; set; }
        public Nullable<int> ID_партнера { get; set; }
        public Nullable<int> ID_услуги { get; set; }
    
        public virtual Partners_import Partners_import { get; set; }
        public virtual Services_import Services_import { get; set; }
    }
}
