//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clean_Planet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_type_import
    {
        public Service_type_import()
        {
            this.Services_import = new HashSet<Services_import>();
        }
    
        public int ID { get; set; }
        public string Тип_услуги { get; set; }
        public Nullable<double> Коэффициент_сложности_услуги { get; set; }
    
        public virtual ICollection<Services_import> Services_import { get; set; }
    }
}
