//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clean_Planet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_import
    {
        public Services_import()
        {
            this.Partner_services_import = new HashSet<Partner_services_import>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Тип_услуги { get; set; }
        public string Наименование_услуги { get; set; }
        public string Код_услуги { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
    
        public virtual ICollection<Partner_services_import> Partner_services_import { get; set; }
        public virtual Service_type_import Service_type_import { get; set; }
    }
}
